git-cherr-pr: report error cleanly when given bad branch

diff --git a/git-cherry-pr b/git-cherry-pr
--- a/git-cherry-pr
+++ b/git-cherry-pr
@@ -64,7 +64,9 @@ if test "${origin}" = ""; then
     # First, try to read from local branch configuration, if that exists.
     if ! origin="$(git config "branch.${branch}.remote")"; then
         # Second, check existing remote branches
-        origin="$(git branch -r | sed 's/^\s\+//' | grep "^\([-a-z]\+\)/${branch}" | cut -d/ -f1)"
+        if ! origin="$(git branch -r | sed 's/^\s\+//' | grep "^\([-a-z]\+\)/${branch}" | cut -d/ -f1)"; then
+            err "Failed to find remote for branch ${branch}"
+        fi
     fi
 fi
 
